### PR TITLE
reorganized xml for better skinning support

### PR DESCRIPTION
**Pull request by tycoo**
main contents are grouped into seperate boxes, which can be easier moved and placed, respective the skinners preferences; e.g. the current program info to top and the epg window down, without loosing the inner settings, distances and invisible buttons.

cheers

### CODE REVIEW

**Comment by primaeval** [comment]
Thanks. 
Who are you on the Kodi Forum?
Did you have a look at the CatBar skin too?

**Comment by tycoo** [comment]
i am not registered at kodi yet ;p but i am following your thread since a few days now and started skinning a white theme. took some time to figure out the xml options & functions.
i didnt look into the catbar xml yet, but tested the catbar skin. 
Great work primaeval

**Comment by primaeval** [comment]
Thanks. I blindly trusted some pull requests before and spent weeks tidying up the mess. I just want to make sure nothing breaks this time. ;)
The CatBar skin is a variation of the Default skin with the Category Bar at the top and everything moved down 30. The video box is shrunk to fit and the description expanded a bit.
If you can think of a way to make Default and CatBar a single skin again I would be grateful. I hate keeping 2 similar skins in sync. I did that with the original pip skin.

**Comment by iainsmacleod** [comment]
Any way you can make the Cat bar display when pressing up?

**Comment by tycoo** [comment]
Sure, take your time.

About the categories. I never used them before, nor they are shown on the epg for me.
I didn't configure and set some categories before, but some are catched within xmltv file and i can search for it within your catbar skin button now. 
The other function you are talking about doesnt work for me, and i am not sure what you are trying to achieve exactly.  Perhaps i missed something to configure the tv guide properly? I have to read the forum again i guess

**Comment by primaeval** [comment]
There are 2 sets of categories confusingly. 
The one labelled Category in the top left of the Catbar is the Program Categories from the xmltv file.
The other is the Channel Categories. The only one visible by default is "All Channels".
You have to make the rest yourself.
There is a context menu that can be brought up with c or right click when you are over the "All Channels" button.
You need to Add Category then select the new category and Add Channels.

**Comment by tycoo** [comment]
i close this for now, as it needs some minor changes.

**Comment by primaeval** [comment]
It's a good idea but I need Default and CatBar to stay in sync, especially while I'm working on the new Action Bar in CatBar.

**Pull request closed without merging**
