### PR TITLE
Skin changes

### PR DESCRIPTION
**Pull request by iainsmacleod**

### CODE REVIEW

**Comment by iainsmacleod** [comment]
Wait for additional changes.

**Comment by iainsmacleod** [comment]
Should be good to merge

**Comment by primaeval** [comment]
Did you test every dialog on confluence?

**Comment by iainsmacleod** [comment]
I test loading, channels. main, menu, setup.

The main issue I have found that I was having was the cancel button for
loading on Jarvis, on Krypton it if offset from it's requested location -
so looks weird on Krypon, fine on Jarvis.

**Comment by iainsmacleod** [comment]
Also, programme list

**Comment by iainsmacleod** [comment]
Did you find any issues to prevent a merge?

**Comment by primaeval** [comment]
I was waiting for you to say everything was ok first. It looked like you needed to do something with the cancel button.

**Comment by iainsmacleod** [comment]
I don't think I can make it work in Jarvis and Krypton.

**Comment by primaeval** [comment]
What is wrong with it?

**Comment by iainsmacleod** [comment]
On Krypton the button seems to be offset from the coordinates I enter, so cancel doesn't lie in the button. So I center the text on top of a new image, because I also don't like how the button appears. 

In Jarvis, it is fine.

**Comment by primaeval** [comment]
That is one of the reasons I try not to touch krypton at the moment. I found loads of bugs with the texture layout.

**Comment by iainsmacleod** [comment]
And that's why I sorted it for Jarvis, for your preference.

**Comment by primaeval** [comment]
If all the other buttons line up ok with their textures can't you just copy their formatting rules to the Loading Cancel button?

**Comment by iainsmacleod** [comment]
I would think it would just work, my only assumption would be something is
different in gui.py???

**Comment by iainsmacleod** [comment]
Hid the button, but still works - should be good now.

**Comment by primaeval** [comment]
Is the cancel button wrong on the Default skin in Krypton too?

**Comment by iainsmacleod** [comment]
Default looks fine, I wonder if you specified a bigger button. I removed a lot of the other bits, the loading bar etc, maybe that had an effect?

**Comment by primaeval** [comment]
I don't think I touched the loading screen from the original except for the background.

**Comment by primaeval** [comment]
I tested it. You have taken out too much from the loading screen. It flashes up on every new page. There was some background texture that covers that unless it takes a long time. You might need to try it out on a lower end device if you don't see it on your dev system.

**Comment by iainsmacleod** [comment]
Are you suggesting your default skin does t show the loading screen when it
is loading some items?

I see what you are talking about, but it is actually loading. I guess I
could make a transparent background if media is playing.

What are you looking for?

**Comment by primaeval** [comment]
Do a comparison of paging down in the main epg with the Dark skin. Check out my master then your master and you should see that your latest changes flash up the pulsating loading icon when you page down. It didn't do it before.

**Comment by iainsmacleod** [comment]
I know what it is. There is an animation associated with the control, and
there is a delay of 1.5 seconds. I guess, I'll put the animation delay back
in - but 1.5 s seems pointlessly large. I think if there's is about 500ms
I'm good. Let me know if that works for you.

Lowest system I have is Pi2

**Comment by iainsmacleod** [comment]
Hmm. Found some scenarios it still blinks. Will leave at 1500 I guess.

**Comment by primaeval** [comment]
That's better. Thanks. 
I spent a lot of time early on trying to work out why I was getting headaches paging down in a dark room. I had to do some sneaky tricks to hide some of the epg when it was changing. 
It's still not perfect (for all skins) but its not too distracting now.

**Pull request merged**
