### PR TITLE
Dark skin fixes

### PR DESCRIPTION
**Pull request by iainsmacleod**
Got OSD information working again.

### CODE REVIEW

**Comment by primaeval** [comment]
There are a few conflicts so you'll have to merge in my master first and fix the differences.

**Comment by iainsmacleod** [comment]
Hmmm, when I look at my GitHub app it says that master is up to date with primaeval/master? Any ideas?

**Comment by primaeval** [comment]
It should say you are ahead of me. Check you have fetched from upstream and merged from the tracking branch.

**Comment by iainsmacleod** [comment]
I keep trying to sync but it doesn't appear to be working. I think I have royally messed something up. last changes I see from you are 0.0.60

**Comment by iainsmacleod** [comment]
Did I mess somethingup with this https://github.com/iainsmacleod/script.tvguide.fullscreen/commit/cb6eb3db4d0fe46627c6f0711a83a577572216b5 ?

**Comment by primaeval** [comment]
I can't really see what is wrong. It might be.

**Comment by iainsmacleod** [comment]
DO you know how I can blow mine away and overwrite with yours?
I have my changes saved, so should be easy to merge, but I am in a crappy position right now.

**Comment by iainsmacleod** [comment]
I'm sorry to be so much trouble.

**Comment by primaeval** [comment]
Save your work folder somewhere else before you start experimenting!
You can do hard resets to your branches to get them back in sync.

**Comment by primaeval** [comment]
It doesn't look like you have pulled in my changes since you made a fork.
This might help.
http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by primaeval** [comment]
This is the main part:
https://help.github.com/articles/syncing-a-fork/

**Comment by primaeval** [comment]
Have a look at this diagram to see what is going on:
https://github.com/primaeval/script.tvguide.fullscreen/network

**Comment by iainsmacleod** [comment]
Thanks for all the info, will give it a read.

**Comment by iainsmacleod** [comment]
Chief, I have been reading this stuff and have tried several things - I
have no idea how I can't get it to work. At this point I have my work
saved, do you know how I can just totally overwrite my master with your
original and then add my changes and do a pull request - it all sounds
simple.  Also, I guess when I add changes I publish to my master, then I
ask for a pull from my master to yours?

**Pull request closed without merging**
