### PR TITLE
Dark Skin changes

### PR DESCRIPTION
**Pull request by iainsmacleod**
Button and layout

### CODE REVIEW

**Comment by primaeval** [comment]
I'm working on an external player scheduler that will be similar to Autoplays. It will need another button in the menu with id 4009.

**Comment by iainsmacleod** [comment]
To replace the current autoplay?

**Comment by primaeval** [comment]
No. A new one. 
So there will be Remind, Autoplay, External Play which eventually have the option to be Once, Always, Same Time, Same Day in a select dialog.

**Comment by primaeval** [comment]
Plus there will have to be somewhere to put some buttons for the lists for touch screen devices: Listings, Now, Next, Search, Reminders, Autoplays, External Plays.
There are going to be a lot of options eventually so it might need some thought how to lay it all out.

**Comment by iainsmacleod** [comment]
I will have space, I think, to add another 4 buttons. I'll wait to see what
major changes you make.

**Comment by primaeval** [comment]
If there are too many it will be better to add a submenu or select dialog. 
I'm making progress the AutoPlayWith feature (play with an external player).

**Comment by iainsmacleod** [comment]
What's the use case for the feature?

**Pull request merged**
