### PR TITLE
a new quick epg view

### PR DESCRIPTION
**Pull request by im85288**
can be shown by pressing up/down in tv mode.

I put defaults in the skin sections beginning with control id 10000. Should be straight forward to port across the skin versions.

### CODE REVIEW

**Comment by primaeval** [comment]
Something I want to add in is a Listings view per channel. 
See the functionality in my TV Listings (xmltv) addon for details.
It uses the standard List View but it would look better with a custom skin.
Is this something you could do, seeing as you are getting good at all these popup windows?

**Comment by primaeval** [comment]
It's in 0.0.81 but it still needs the autoscroll fix.

**Comment by im85288** [comment]
It should be very similar to the changes made for the quick epg with the exception that scroll left/right would not be needed. I do not have the time to implement it though, but if you need any assistance feel free to ask and I'll try my best to help out.

**Comment by im85288** [comment]
In theory the autoscroll should work? The data is only updated once now..with only the counter being updated repeatedly.

eg

if remainingseconds < self.upNextTime and remainingseconds > 1:
                        firstTime = True
                        self._updateNextUpInfo(firstTime)
                        firstTime = False
                        self._showControl(self.C_UP_NEXT)
                        count = 0
                        while remainingseconds < self.upNextTime and remainingseconds > 1 and self.mode == MODE_TV:
                            self._updateNextUpInfo(firstTime)

**Comment by primaeval** [comment]
I looked too quickly. I didn't see the firstTime flag even though I was staring at it. ;) Sorry. You are right.

**Comment by im85288** [comment]
No probs, I haven't tested it but it should work :)

**Comment by primaeval** [comment]
Has sky tv got all these features or did you just come up with them?

**Comment by im85288** [comment]
Yeah a bit of both really, having used sky and for example vu+ they both have things like the quick EPG. In fact the vu+ has a zap history (let's you choose from a list of previously watched channels..but I prefer the simple option). The next up thing was just based on my addon though. 

The only other thing that could possibly make things better would be to provide some sort of PVR feature to allow scheduling/recording of programs...not sure how that would be implemented though!

**Comment by primaeval** [comment]
I've got scheduling set up in TV Listings (xmltv). It plays and stops channels using the built-in Kodi scheduler.
If you have got a recording player set to the default player in playercorefactory.xml it should record it.
I couldn't see a way to make it switchable between play/record without rewriting the core Kodi player.
Lots of the addons need user interaction to pick the stream from a list too which makes scheduling even more tricky.
Some people in Team Kodi also seem to get quite nervous when you talk about recording streams.

**Pull request merged**
