### PR TITLE
Dark footer fix

### PR DESCRIPTION
**Pull request by iainsmacleod**

### CODE REVIEW

**Comment by primaeval** [comment]
Thanks

**Comment by primaeval** [comment]
The charcoal file has to be in the special folder because I'm moving it out of the zip so it only gets downloaded once. There is a bit of code in addon.py that pulls it down from github and puts it in the addon_data folder.

**Comment by iainsmacleod** [comment]
OK, did you need me to do something?

**Comment by primaeval** [comment]
If you could just put the charcoal.png paths back to "special://profile/addon_data/script.tvguide.fullscreen/backgrounds/charcoal.png" I'll merge it and get another release out.

**Comment by primaeval** [comment]
I fixed that. There have been a few more buttons and things added recently. I don't think any of them break your skin but you might want to add them in when you have time.

**Comment by iainsmacleod** [comment]
Did you fix it in all the xml fies, I reference it in a few.

**Comment by primaeval** [comment]
Yes. It saves a fair bit of bandwidth at 2M a pop. ;)

**Comment by iainsmacleod** [comment]
I apologise, I didn't realize.

**Comment by primaeval** [comment]
No problem. Github have been footing the bill. ;) Thanks Github. I just notice it when I've made a series of changes and downloading the new version seems to take forever.
I've added a similar texture for my skins and maybe planning on making a selection of backgrounds.

**Pull request merged**
