### PR TITLE
allow info to be toggled for quick epg

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by im85288** [comment]
@primaeval and @iainsmacleod - this PR let's the Info button toggle showing the program description in the quick epg. To get that to work it toggles the program description control's (17022) visibility. Have a look at the sly skin changes to see how I used that visible flag for showing other things like the time etc

Imgur

**Comment by primaeval** [comment]
Ok it's in. Thanks.
@iainsmacleod I've added it to Dark but you might want to see if it fits in with your scheme.
I'll release it sometime tomorrow if you can check it first.

**Comment by iainsmacleod** [comment]
It's fine by me. I might take out some of the info, as it may be a little
redundant. The time needs a slight adjust to the left (4:00-5:00pm..pm is
getting cut off.)

**Comment by iainsmacleod** [comment]
So how do I toggle displaying the information or not? It's not a skin
setting or key command - just configured visible or not.

Anyone else think that quick EPG should show this if I press info, and it
should show the "remind screen" if I press context menu - just like full
EPG? And by extension, a pip mode for the menu setup screen would be great.

**Comment by im85288** [comment]
Yes quick epg does show it when you press info. It will then remain showing until you press info again to toggle it. 

I do like the idea of adding the context menu..will take a look at that soonish

**Comment by im85288** [comment]
@iainsmacleod - I added the context menu to quick epg in this PR https://github.com/primaeval/script.tvguide.fullscreen/pull/60/commits/ec7dad6c4b424cf52a5b584eb69580a6013a6059

**Comment by primaeval** [comment]
You can easily just add the video window to the main menu to show what is now playing.
It is probably best to put it where the program image is now and make that invisible when HasMedia is true.

**Pull request merged**
