### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**
30 minute auto refresh of epg

### CODE REVIEW

**Comment by primaeval** [comment]
I can't see what you've done as the whole file looks changed. 30 minutes is too much for any server. You'll probably get banned for spamming them.

**Comment by ghost** [comment]
check update timebar and # find nearest half hour refreshes the guide not the interval data

**Comment by ghost** [comment]
send me your email if you want

**Comment by primaeval** [comment]
Look at the file diff. You've probably used the wrong line endings. Every single line is changed.
https://github.com/primaeval/script.tvguide.fullscreen/pull/114/files

**Comment by primaeval** [comment]
You need to change the line endings and make another commit so I can see what you've done. There should only be a few lines that have changed in the diff, not the whole file.

**Pull request closed without merging**
