### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Zomboided**
Add VPN Mgr support, allowing VPN connection filtering to be used when using different add-ons within the TV guide.

Works by checking and changing a connection before an add-on is used to provide a stream.

Works entirely independently and will not cause errors if VPN Mgr is not installed.  Requires no user install/setup beyond what's required by both Fullscreen and VPN Mgr already.

I'm not confident that I have covered every situation here (such as autoplay and playwith).  If there are other blobs of code that end up calling a stream from an add-on, I can look at those (I started to look at the PlayMedia calls but couldn't tell if they were being fed add-on streams).

Cheers

### CODE REVIEW

**Comment by primaeval** [comment]
I need something to test with before I pull this in. Have you got any ideas? I sent you my email if that helps.

**Comment by primaeval** [comment]
Ok. Let's try this. If it breaks the forum rules I'll have to ditch it but I think it is ok.

**Comment by Zomboided** [comment]
Good news! Cheers

**Comment by Zomboided** [comment]
I'll do a how-to on my GitHub wiki today on how to set it up.

**Pull request merged**
