### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by iainsmacleod**

### CODE REVIEW

**Comment by primaeval** [comment]
You managed to merge. Good. :)
A couple of things.
I think the channels and streamaddon dialogs should be copied in from Default. I made them fullscreen today.
Are you sure about the red time marker? It seems to look like a river of blood to me and clashes a bit with the cyan channel highlight. It was just a couple of pixels wide in the original I think which might help.

Have a look at the new Default and pip skins and see if things match up ok with Dark.

I incorporated a lot of your ideas into the Default and pip skins, so they all look quite similar now. Thanks.

**Comment by iainsmacleod** [comment]
I have no problem with changing from the red, I have grown to like the cyan. I am not sure what you mean about the dialogs, I did a compare in notepad++ and I don't see any major dialog differences.

**Comment by iainsmacleod** [comment]
Do I close this pull request now? Or do I wait for you to close it? I really need an idiots guide to this.

**Comment by primaeval** [comment]
Copy in the files script-tvguide-streamaddon.xml and script-tvguide-channels.xml from Default to Dark. 
If you are sure you are ok with a cyan time marker change the main xml file too.
Then make sure you have pulled in all my latest changes so we are in sync and I'll pull this request from you.

Make sure you try to test every strange case you can think of. Try to break your software before your users do.

**Comment by iainsmacleod** [comment]
I made  change to the cyan, and then I made a change to the background. I
did not just do a straight copy of the files, as there are a few
differences. I reall have a sinking suspition something is not right with
the Git setup, I am not sure how to properly do a pull request.

Do I make changes locally,, commit to my master, then do a pull request
from my master to yours?

**Comment by primaeval** [comment]
Make sure you do a Fetch From my repo and merge in the changes.
Then the only changes in the pull request will be your master additions to my master.
You can always make a branch that you just sync with my master so that you know where you are in relation to mine.
Always have a look at the Visualize All Branch History in git gui to see what is what.
It takes time to get your head around.

**Pull request closed without merging**
