### PR TITLE
Initial Up Next support

### PR DESCRIPTION
**Pull request by iainsmacleod**

### CODE REVIEW

**Comment by primaeval** [comment]
It seems a bit cramped. ;)
Did you try my version of the Dark Up Next popup?

**Comment by iainsmacleod** [comment]
No sorry.

**Comment by primaeval** [comment]
Have a look at the current master. You might need to make a new temp branch to pull it into.

**Comment by iainsmacleod** [comment]
OK, I had a look, I will adjust due to cramp-ness, but otherwise I prefer
the smaller notification without the time - I see what you were doing, but
I think it is a lot for a pop-up (I considered the same layout)

**Comment by iainsmacleod** [comment]
So let me know how you feel about the mouse layout - right now I have about 60 width on the buttons.

As for the next up, I want to keep it small since it is akin to a pop-up. Let me know if you would like to see more changes - fyi, I don't think autoscroll works within this control for program description.

**Comment by primaeval** [comment]
The mouse buttons need to be pretty huge to work on a phone.
Working on a 1280x720 5inch phone way one of the main reasons for starting this project.
Making everything Fullscreen, minimal and big are the criteria that make it possible.

I do my testing with some lorum ipsum. Find out were it sets the description in the code and replace it with a big chunk of lorum. http://www.lipsum.com/

The scroll problem is strange. I tried it with autoscroll and nothing happened.
@im85288 Do you have any idea why?

**Comment by im85288** [comment]
Sorry guys no idea, I only use the addon with a remote control.

**Comment by primaeval** [comment]
It should be the same everywhere.
The problem is just that the Up Next program description doesn't autoscroll but the main epg description does. They both use textboxes and both have autoscroll animations.

**Comment by iainsmacleod** [comment]
I have no issue with modifying for larger buttons, but something will have
to be sacrificed, I will look into it.

**Comment by iainsmacleod** [comment]
I wondered if it was something to do with the countdown, causing a refresh
on the control and therefore resetting a counter. If you put time below
1000ms, you see it start to scroll, but it resets.

**Comment by im85288** [comment]
Ahh I see what you mean now, yes it's probably getting refreshed every second so restarting...there's probably a more efficient way to do it to just update the counter once the other values had been set once.

**Comment by iainsmacleod** [comment]
Maybe the countdown has to be a separate control?

**Comment by im85288** [comment]
I'll take a look into it as it should be an easy fix :)

**Comment by primaeval** [comment]
I try to get rid of any animations in my skins because my kids rpi box just can't cope with them.
I made a special skin with zero time animations just for it. skin.confluence.wall.

Does it work with zero time animations?

**Comment by iainsmacleod** [comment]
I have a OnePlus2 and was going to check, but I cannot connect to your repo
after installing it from zip - any ideas. I'll look into logs, I'll install
addon on its own.

**Comment by im85288** [comment]
The counter is just there to signal it getting closer to the next show (closes 1 second before end of play) and the way it is now it updates all the info every second. My change will get it to do that only once and do the counter repeatedly. So that should fix the autoscroll issue

**Comment by primaeval** [comment]
So its a new textbox every second effectively.

**Comment by primaeval** [comment]
If you want to try it on your phone you could test out my skin.naked skin.
All the fonts are huge and the functionality is minimal but enough.
It needs some tweaks but its good enough for watching stuff on your phone.

**Comment by iainsmacleod** [comment]
Guys, could we make the pop-up have two timers, one for appear and one for
length to appear. I would like to show the pop-up 3 minutes from the end of
the show, but only show it for 20 seconds - since I rarely stay with a show
until the end, due to credits and commercials. Follow me? Thanks

**Comment by im85288** [comment]
Yeah sounds like a good idea, i can add a setting to set how many seconds it shows for which should let you achieve the same result. Probably more useful than coming on at the end and staying on constantly.

**Comment by im85288** [comment]
I just sent a PR for a new quick epg view (check here for a screenshot: http://forum.kodi.tv/showthread.php?tid=282157&pid=2400802#pid2400802) 

It has the defaults in your skin so you just need to adjust the control block 10000 and below to your guide. Works really well :)

**Comment by im85288** [comment]
This commit should provide what I discussed above for the next up : https://github.com/primaeval/script.tvguide.fullscreen/pull/24/commits/93719311038787724fa7ed4dbb307563a46c672b

**Comment by primaeval** [comment]
There already is the Remind functionality to popup 5 minutes before the end of a program.
Make sure that still works with any changes you make.

You get the quick epg for free with the Default skin and it's fullscreen. ;)

**Pull request merged**
