### PR TITLE
re-add skin tweeks, removed video window from menu setup

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by primaeval** [comment]
I don't like the small size menu dialog but I can see you are probably trying to keep the quick epg visible underneath.

The category list needs some indication that it is a scrollable list and which category is currently activated. Some of the other original lists do too but they need some indicators as well in every skin.

It is pain to get to the Add Category button and back down again when there are lots of categories set up.

There is no need for the Remove Category button. Just press OK without selecting any channels and it will disappear the next time you start the guide.

The black highlight colour on black buttons in the Stream Setup dialog makes the selected channel disappear in Addons and Browse.

I'll make a full featured Category handling dialog like in the main Kodi PVR sometime when everything else has been fixed.

**Comment by im85288** [comment]
I don't recall having a black highlight on stream addons, this may be down to a lot of my changes getting overwritten when you merged then overwrote what I did earlier. I appreciate the feedback but I'm happy with the design as I have it now. My thoughts are as long as the default skin provides the core functionality other skins should be able to do as they please but I think we differ on those sentiments.

I'll send a PR to remove the skin tomorrow as I don't have time today (too busy watching season 2 of narcos!). Cheers

**Comment by primaeval** [comment]
Its ok I'll just take your skin out now if you don't want to be in this project any more.
You have made some great additions to this project. I hope your next one goes more calmly.

**Comment by im85288** [comment]
Cheers yeah please do, feel free to keep the other additions in I have made or remove them if you prefer. If it wasn't for a post of yours I saw in the libreelec forums I would never have discovered this wonderful addon in the first place. Thanks and good luck going forward.

**Comment by iainsmacleod** [comment]
I think these were directed at me. I made the changes were possible.

Can you please elaborate on the following:

"small size menu dialog but I can see you are probably trying to keep the
quick epg visible underneath"

Add category can be accessed pressing left from anywhere in the category
list.

"black highlight colour on black buttons in the Stream Setup dialog makes
the selected channel disappear in Addons and Browse"

Not sure I see what you mean - I noticed the sign into BBC is blank, until
I dig down and come back up - but I couldn't see how to fix that.

Let me know your thoughts.
Thanks

**Comment by primaeval** [comment]
@iainsmacleod All the comments were about sly. 
The only things I spotted about Dark were the second video player peaking through the menu and the default menu program picture staying there when there is a program picture from the xmltv.

**Comment by iainsmacleod** [comment]
All that and more should be fixed now.

**Comment by primaeval** [comment]
Thanks.

**Pull request closed without merging**
