### PR TITLE
a few more tweeks

### PR DESCRIPTION
**Pull request by im85288**
final one for now, just harmonised the date format and aligned the time and date on the EPG.

Sorry..thought I would have squeezed it in the last PR!

### CODE REVIEW

**Comment by primaeval** [comment]
I was just about to make a release. ;)

**Comment by im85288** [comment]
Cheers! I've got the day of work so tweeking away! Not really much more skin tweeking to do though..might start looking at the press 0 for going to last played channel...unless you have it covered?

**Comment by primaeval** [comment]
Give it a go. I just added info to close the epg for my rpi.
I added some defensive programming to the database exceptions that freeze the addon.
See if you can break the osd by going past the programs that are available.

**Comment by im85288** [comment]
I'll have a play, problem is I have 5 days worth of EPG...though that I know is overkill!

A couple of things that I feel need fixing eventually (though not critical at all) is the OSD is only updated upon showing/cycling through channels. So if for example you have the OSD open and a new program starts the OSD is not updated with the new details (image, program name etc)

Another one is that the EPG start time remains on when you first opened it, so if you have watched something for a couple of hours and go back to the EPG you need to navigate right to get to the current start time. Not sure if that's an easy one to resolve.

**Comment by im85288** [comment]
Sorry one more teeny tweek for the osd image placement coming

**Comment by primaeval** [comment]
The more I use this the more bugs I find too. They must have been in there for years.
The android black screen bug is really annoying me now. Also when I change channel in tv mode in android it pings me back to the epg. Windows and LibreELEC work ok.
If you can work out any fixes please add them in.

**Pull request merged**
