### PR TITLE
Major menu latou changes

### PR DESCRIPTION
**Pull request by iainsmacleod**
Trying to mimic the stream setup layout.

How can I add a prgramme image to the menu section in gui.py? So I can call it up on the menu screen?

### CODE REVIEW

**Comment by primaeval** [comment]
There is a programme image there already.

**Comment by primaeval** [comment]
The background video needs to be completely hidden by one big texture or the video will be drawn twice. 
My little rpi can't cope with that.

**Comment by iainsmacleod** [comment]
Just so I'm clear you reverted my changes because I have two PIP? One from
the menu, and one from the stream add-on? Or are you suggesting one from
the main and one from the menu?

Regarding the programme picture, I need it on the stream setup page.

**Comment by primaeval** [comment]
In the menu dialog one video shows through under the first green bar. That means that the whole video is getting drawn twice: in the background and in the pip window. Usually there is some optimisation in Kodi or the os to not draw fully occluded video windows.

I'll test the changes in a seperate branch next time before adding them in. It didn't look like a major change until I tested out the dialog box.

**Pull request merged**
