### PR TITLE
re-add block out image when media not playing

### PR DESCRIPTION
**Pull request by im85288**
And remove the setting of channel background image in gui.py as it messes with the skin backgrounds for quick epg and the normal epg

### CODE REVIEW

**Comment by primaeval** [comment]
That messes up the other skins.

**Comment by primaeval** [comment]
You need to do a thorough test with all 4 skins when you make a change in gui.py.

**Comment by im85288** [comment]
In what way? It was like that previously

**Comment by primaeval** [comment]
It broke the other skins matching up with the footer.

**Comment by primaeval** [comment]
Also the Setting Show Background Image depends on it.

**Comment by im85288** [comment]
Oh your meaning the image height change...yeah that's fine. Didn't know about that..but I have left that in. What change here messes things up?

**Comment by im85288** [comment]
Sorry my description was not very good. This removes this code that was added:

`try:
                        if self.currentChannel == channels[idx]:
                            control.setImage("tvguide-program-grey-focus.png")
                        else:
                            control.setImage("black-back.png")
                    except:
                        control.setImage("black-back.png")`

As that forces my channels to have the background above. I guess it was to highlight the current channel but I did not need that for the sly skin so added this code instead:

`if SKIN != 'sly':
                    try:
                        if self.currentChannel == channels[idx]:
                            control.setImage("tvguide-program-grey-focus.png")
                        else:
                            control.setImage("black-back.png")
                    except:
                        control.setImage("black-back.png")`

That should be fine for all skins?

**Comment by primaeval** [comment]
Did you visually check?

**Comment by im85288** [comment]
I checked my skin, but I'm quite confident that my change above would only effect the sly skin so not sure of the issue with this one?

**Comment by primaeval** [comment]
You have to visually check all 4. 
I just spent an hour or so unfixing the sly fixes in the other skins and had to make 2 releases because I didn't realize they had screwed up the other skins.

**Comment by im85288** [comment]
Gotcha, I'll check all 4 with future changes to gui.py as it's sensitive. I think I moved it 5 pixels..but didn't know the consequences!

**Comment by primaeval** [comment]
Things are too precarious in gui.py at the moment. There are a lot of my quick hacks with fixed numbers that should be parameters found in the xml files. It was ok with one skin but now it needs fixing.

**Comment by im85288** [comment]
Yeah I'll treat that area with more caution in future. What I think may be useful is a listings view of programs playing now. I only really want that so that I can add it to a widget listing on the home screen that would show the playing now programs (so emulating what the PVR integration in kodi does). I may start investigating that. If it is successfull we could possibly have another view to show the now playing items..but personally I'm happy enough with an EPG view.

**Comment by primaeval** [comment]
Did you see the Listing view from the main epg (info,i)?

**Comment by im85288** [comment]
No I had not until now, works well. My idea was slightly different though in that it would list all programs playing now...but probably some code I could reuse there :)

**Comment by primaeval** [comment]
Do you mean a Now/Next couple of dialogs?
They should just need a similar query.
We'll have to link them from the main menu or we'll run out of buttons. (maybe number buttons)

**Comment by im85288** [comment]
Sort of, basically emulating the kod PVR where you can have either and EPG view or a Channels view. The channels view for example in Titan is like this [img]http://i.imgur.com/NZWNuU7.png[/img]

I think if we could do it, yeah a number button could flip between epg/channels view

**Comment by primaeval** [comment]
That is a Now view.
Make the simple version with just a select dialog box like the Listings view first.
Then we can debug the functionality without having to debug custom guis.
When it is solid have a go at a custom gui.
See if you can make a reusable one for Now/Next/Listing views.

**Comment by im85288** [comment]
Sounds like a good plan, like I mentioned though I'm not sure I want that view as the epg is more than enough..I just want to see it in widgets :) But starting of simple like the listings view seems the way to go. Football day though 👍

**Comment by im85288** [comment]
Does the meta-search thing work for you? I tried it a couple of times but got no results. Not sure where it is searching anyway?

**Comment by primaeval** [comment]
The Meta search is Meta4Kodi if you have installed it. 
You need some custom players for addons that find movies and tv show episodes. That is getting hard to find these days. I should make it hook into metalliq sometime too but I was trying to keep this possible to add into the main repo someday.
Meta4Kodi searches all the addons at once.
Some of the major movie finding addons have modified their code to stop it working with them.
iSearch does a similar job but only searches one addon at a time. You need Spoyser's repo version to work with the naughty addons though.

**Comment by im85288** [comment]
Ah right thanks for the explanation, maybe eventually it's worth hooking up to tmdb (as extended info and skin helper addons do)

On a different note, do you know if it's possible to get the update timer image to show in front of the EPG as apposed to behind it? I want to use solid textures and it doesn't show through them when behind...probably something simple but tried moving it in the skin XML with no luck yet

**Comment by primaeval** [comment]
That's why I left lots of space in the center column for things you can do with the programs. 
In my TV Listings (xmltv) addon I added sickrage/couchpotato/extended info/meta/isearch.

Which update timer image? Can you post a link or screenshot.

**Comment by im85288** [comment]
Cool, I mean the progress timer thing that shows behind the EPG which shows what the current time is. I think it uses cyan.png in the default skin. ID 4100

**Comment by primaeval** [comment]
The timebar?
The z-order of controls is the order they appear in the xml file.
If you want something nearer to the top of the stack (ie nearer to you) move it down in the file.

**Comment by im85288** [comment]
Yeah I tried putting it at the very bottom but still the epg control buttons were layed out on top. I altered my skin texture to be transparent to get around it as I could not for the life of me find how to do it! Just added those commits above

**Comment by primaeval** [comment]
The program buttons get made on the fly in the onredrawEPG function.
They must end up on top of the timebar.

**Comment by primaeval** [comment]
I want to rename the textures functionally soon so we can get the case statements out of gui.py.
I've started in Default and pip with the buttons using tvg- as a prefix so we can see the difference.
So far I've only got tvg-button-focus.png and tvg-button-nofocus.png for the context menu and stream setup dialogs.
If we can do this for all the textures it will make changes and additions much more pleasant.

@iainsmacleod has a constant for his textcolor. If we can use that or use a dummy label to get the default textcolor that would help too.

**Comment by im85288** [comment]
Sounds good, I've noticed that when playback goes back to the EPG the current program is not set so I'm thinking it re-inits or something. Still no pattern as to when it happens though

**Comment by primaeval** [comment]
There seems to be a lot of race conditions too. 
The db accesses are in a seperate thread so it is down to luck whether the data is ready when the controls need updating.
I think that is the source of nearly all the exceptions.

**Comment by im85288** [comment]
Can you merge this PR and I'll start looking at the now channel listing most likely tonight/tomorrow?

**Comment by primaeval** [comment]
I think you need to pull in my today's changes first. There seem to be a lot of changes that are already in Default and pip in there.

**Comment by iainsmacleod** [comment]
Guys, my constant doesn't work. I've been trying to play with it. I also
have to readd that workaround stuff for textures, because reminders don't
work.

I have my boy this weekend, but will try to get to this stuff at some
point. Trying to keep up :)

**Comment by primaeval** [comment]
Family comes first. Have fun. :)

**Comment by im85288** [comment]
That should be it hopefully....

**Comment by primaeval** [comment]
Are you sure about the bright green and yellow. It burns. It burns. ;)

**Comment by im85288** [comment]
Haha yeah for now I'm happy with it :)

**Comment by Mike-KL** [comment]
@im85288 I agree with primaeval about use of vivid green with white text and then not as vivid yellow/orange with black text, when viewed on large flatscreen TV.  Not sure how the yellow/orange highlight sits within overall and generally calm colour hue of sly skin?

http://forum.kodi.tv/showthread.php?tid=282157&pid=2403037#pid2403037

Whilst preparing this post, looked at images grabbed in the above post on my imac looked as bad as on my TV, very difficult and almost impossible to read white text on green background.

@primaeval 

Think you love hiding functional nuggets within the code ;0
was not aware of "Listing view from the main epg (info,i)?" until reading through this thread :)

http://i.imgur.com/48rXian.png

**Comment by primaeval** [comment]
I just did a fix to tone down the textures and make them transparent in 0.0.89

There are three new views now:
Listings (1), Now (2), Next (3)

**Comment by im85288** [comment]
Did you change the sly skin? I would prefer to do that if so. 

Cool about the new views :)

**Comment by primaeval** [comment]
I changed sly but you can change the textures again later if you like.

**Comment by primaeval** [comment]
We need to take out all the "if sly" conditionals today and use "tvg-function.png" textures today or soon.

**Comment by im85288** [comment]
Yeah just tested it and I'll be changing it, I don't like the transparency. For the sly skin can you let me make the changes as skins are personal taste and what's good on one persons eyes is not necessarily good in another persons eyes. When I change I'll look into removing the if statement. Cheers

**Comment by primaeval** [comment]
The skins need to fit together as we are presenting a unified package.
That means that the background image has to work the same way in all of them and be seen through the transparency.
If you want something personal you can fork this addon and do what you like with it but release it under a new name.

**Comment by im85288** [comment]
No worries, it's only two images and I'll be changing them anyway. The only problem previously was the white on green text. I'll fix that and all should be fine. No need to do another fork/release as that was why I added my own skin version :)

**Comment by Mike-KL** [comment]
@im85288 colour changes applied by Primaeval at 0.0.89 are not that severe, colour change needs to be applied to the time through programme "time bar" to retain overal colour consistency.

http://i.imgur.com/GyL1Flg.jpg
http://i.imgur.com/vOrEs64.jpg

**Comment by im85288** [comment]
Yeah I agree with that, I wanted the timebar on top but that proved difficult to achieve. I'm thinking of changing the colours totally (for now playing/highlight) any suggestions?

**Comment by im85288** [comment]
Actually scrap my previous comments, I tried on my TV down stairs and I like the way it is now.

@Mike-KL  - do you agree or feel more changes are needed?

**Comment by im85288** [comment]
@primaeval - How do I call up the Now/Next listings?

**Comment by primaeval** [comment]
Listings (1), Now (2), Next (3)

**Comment by im85288** [comment]
Listings(1) works but not 2 or 3 (for me at least)

**Comment by primaeval** [comment]
menu, info and end work at the moment but I don't think they should be like that eventually.
I was just fishing for spare buttons.
https://github.com/primaeval/script.tvguide.fullscreen/blob/b1dea6c3011da2c373623c781cb238a3a87acf73/gui.py#L526

**Comment by Mike-KL** [comment]
@im85288 @primaeval 

I like the changes, colouring is more relaxed

Listings, works.. Now and Next dont work (same as im85288) using standard CEC remote settings for overall ref.

**Comment by primaeval** [comment]
I'm open to any button changes if they work on most remotes.

**Comment by primaeval** [comment]
The list of possible buttons is at the bottom of this page:
http://mirrors.xbmc.org/docs/python-docs/16.x-jarvis/xbmcgui.html

**Comment by im85288** [comment]
Yeah Now/Next not working for me either, if I change the code to use the zero or one button it works...but 2 and 3 seem to be playing up!

**Comment by primaeval** [comment]
You'll have to look in your userdata\keymaps folder to see if they have been hijacked.
I had 2 and 3 set up to play and pause for a crappy android remote.

**Comment by primaeval** [comment]
It only works from the main epg window right now too.

**Comment by im85288** [comment]
Yeah that was it, for libreelec it uses the jumpsms buttons. Just sent a PR to fix it https://github.com/primaeval/script.tvguide.fullscreen/pull/43

**Comment by primaeval** [comment]
Let's see what @Mike-KL gets working too and I'll make a release.

**Comment by Mike-KL** [comment]
OK, checked and empty user kemaps folder, tried again from main guide window, 1 works with 2 & 3 not working.  (For ref via CEC using LibreELEC and latest nightly milhouse build)

**Comment by primaeval** [comment]
What device are you on?
Will the sms commands work for you?

**Comment by im85288** [comment]
I'm sure it will be the same for @Mike-KL 

The system usermaps  are located elsewhere

**Comment by primaeval** [comment]
I'll make a release and we can try it.

**Comment by primaeval** [comment]
@Mike-KL try 0.0.90

**Comment by Mike-KL** [comment]
@primaeval 0.0.90 Now and Next working, using buttons 2 & 3

**Comment by primaeval** [comment]
Good.

**Comment by primaeval** [comment]
Thanks @im85288

**Comment by im85288** [comment]
No probs :)

**Pull request merged**
