### PR TITLE
Uploading Dark UI

### PR DESCRIPTION
**Pull request by iainsmacleod**

### CODE REVIEW

**Comment by primaeval** [comment]
Does it work ok with the new progress bars from im85288?

**Comment by iainsmacleod** [comment]
Where are the progress bar's deployed? I will check.

**Comment by iainsmacleod** [comment]
That would be no. I will have to find out how to apply them.

**Comment by iainsmacleod** [comment]
So do I leave this open, or do I close it?

**Comment by primaeval** [comment]
Leave it open. Your new changes will get added on top and appear after these comments.

**Comment by iainsmacleod** [comment]
Ok, I think that should be it???

**Comment by im85288** [comment]
Heads up, on my PR I just added a new section for viewing the last played channel. It's basically a clone of the osd section (6000) but instead uses (8000). The default and pip skins have been updated with a version where it's set to false so good to copy that...or alternatively just copy/paste your whole 6000 section and rename everything to the 8000 range.

Cheers

**Comment by iainsmacleod** [comment]
Thanks for the info, if primaeval accepts my changes I will work on leveraging this feature if yours are also merged.

**Comment by iainsmacleod** [comment]
I would love if you could pull focusColor through to the main XML, so I could change it on the fly if needed.

I guess I could change gui.py similar to what you have done:

if SKIN == 'sly':
            focusColor = '0xFF00B8FF'
elsif SKIN == 'Dark":
            focusColor = '0xFF00FFC6'
else:
            focusColor = '0xFF00FFFF'

**Comment by im85288** [comment]
Yeah I think that's the only way to do it, on the fly would be cool but not sure if the addon can read skin variables.

**Comment by primaeval** [comment]
There are lots of dummy placeholder controls to pass variables to gui.py from the xml and vice versa.
Set an invisible label up to hold the focusColor then it shouldn't need the if SKIN logic.

**Comment by primaeval** [comment]
I pulled in im85288's first so this change needs the new 8000 controls to work.

**Comment by iainsmacleod** [comment]
That should be it.

**Comment by primaeval** [comment]
Thanks.
Just pull in the latest changes from my master branch first and check there are no conflicts in the other skins and I'll merge it in.

**Comment by iainsmacleod** [comment]
Ok, I think I got it.

**Comment by im85288** [comment]
Sorry to be a pain but I just sent in a PR for having a next up window. I added defaults to this skin though in the PR.

**Comment by primaeval** [comment]
Can you add into Dark too. Its in the main master branch now.

**Comment by primaeval** [comment]
The actual logic needs looking into too. At the moment in only searches in the 2 hour viewing window in the epg not in the whole database. That is probably not just a tweak. ;)

**Comment by primaeval** [comment]
Hmm. Maybe it doesn't. But it does get confused when there are missing programs in the schedule and you try to move about in the osd.

**Comment by primaeval** [comment]
Dark is back in now. Thanks.
The Up Next popup needs wiring in though for Dark.

**Comment by iainsmacleod** [comment]
OK, where do I find the code for that?

**Comment by im85288** [comment]
Check out the 9000 block I added to your skin. Look at mine for details if needed.

**Comment by iainsmacleod** [comment]
Yup, yup - there is a lot to look configure. I will work on it, but keep it disabled for now. Thanks for applying to the skin.

**Pull request merged**
