### PR TITLE
bit more skin tweeking

### PR DESCRIPTION
**Pull request by im85288**
pops up a up next info for the next episode (I added defaults to the default/pip/dark) skins

### CODE REVIEW

**Comment by iainsmacleod** [comment]
Is there anyway that you can make the next up notification only visible when the media is playing, and in the foreground? For my skin it will appear behind the EPG due to the transparency I use.

**Comment by im85288** [comment]
It should only be appearing when gui.py is in TV mode (so not when things like the OSD or EPG are being shown). Are you experiencing something different..or did I mis understand?

**Comment by iainsmacleod** [comment]
Yeah, I am experiencing it on EPG screen, maybe I should look at your
visible commands - because you set it to false, and I simply changed it to
true - maybe it needs conditions???

**Comment by primaeval** [comment]
I got it on the epg screen once today too.

**Comment by im85288** [comment]
There could well be a bug or two there I guess, but the logic should only kick off when in tv mode so not sure how it's shown on the EPG.

**Comment by primaeval** [comment]
I just added a couple of changes to fix it.
Any action will close the up next popup.
Select (enter) will also close the popup.

We'll have to have a look at whether all the commands are logical and consistent sometime.

**Comment by primaeval** [comment]
You could get it to stay in front of the epg if you set the time to a large number and press stop in tv mode.

**Comment by im85288** [comment]
Ah yes of course, another way to resolve that would be to do a check on the mode in the while loop and if the mode was no longer tv close it. But having actions to close it makes sense too.

**Comment by primaeval** [comment]
The close on all actions catches everything.
Is there any case where it doesn't make sense to close it?

**Comment by im85288** [comment]
No, sounds good to me. I'll add in the check for tv mode at a later stage as a further safety check.

**Pull request merged**
