### PR TITLE
Start prep for plugin content

### PR DESCRIPTION
**Pull request by im85288**
Having problems getting this to work but wanted to push the code out just in case anyone else knows how to get this going

This needs to be added to the addon.xml

<extension point="xbmc.python.pluginsource" library="plugin.py" />

But nothing works :(

### CODE REVIEW

**Comment by primaeval** [comment]
What is it supposed to do?

**Comment by im85288** [comment]
Eventually I want the plugin.py to provide an entry point to listings (in this particular case I have started with the channels now listing). It's what various plugins/addons do (for example skin helper).

So it would allow for example to go to the widget selection in skin shortcuts and browse to this endpoint to display the now playing channels in a widget...

Another way to call it would be something like 

`plugin://script.skin.tvguide.fullscreen2/?action=pvrchannels`

Still a little bit off but close...ish I think

**Comment by im85288** [comment]
Adding this to addon.xml

`<extension point="xbmc.python.pluginsource" library="plugin.py" />`

Should set it up as a plugin source...but it messes with the other entry saying it is a python script

**Comment by primaeval** [comment]
Something changed recently about the way extension points should be written. You'll have to look up the docs.
I only use confluence, so you are treading a new path with skin widgets. 
There is something like it with a mini-epg in the noobsandnerds stuff I think.

**Comment by primaeval** [comment]
If you have a second addon called script.skin.tvguide.fullscreen2 make sure all the paths inside match.

**Comment by primaeval** [comment]
If you have a big change its best to branch off with the new feature for a while and save the master for small changes.

**Comment by im85288** [comment]
It's going to have to go on the backburner for a bit...but so frustrating as it's so close to being useable. Skin Helper does it a lot but is not a launch-able addon as this one is. I'm one of the devs on the Emby for Kodi addon too and we have it in there..but that is a video addon and the entry point is again not an executable python script (as this one is) 

`<extension point="xbmc.python.script" library="addon.py">
            <provides>executable</provides>
    </extension>`

It may well be something different...

**Comment by im85288** [comment]
Yeah agree, I may just delete it for now. Just wanted to post it in case you or anyone else had an idea of how to complete it.

**Comment by primaeval** [comment]
Keep it in a branch in your fork for now.

**Comment by im85288** [comment]
Will do, I'll give it another attempt tomorrow and if still no joy give up as it's not a massive deal...but I would like to see it :)

**Comment by primaeval** [comment]
We are in full dev mode right now so its probably best to at least start on all the possible features that we can think of now while are brains are in gear, even if they get pushed to a branch until they can be finished.

**Comment by im85288** [comment]
Sure, I'll push this one to a dev branch on my fork and hope some inspiration comes along soon!

I like the now channels listing...but I'm not sure I would use it in place of the EPG (so not sure if it needs a custom window/dialog). One improvement I think can be made there is the select action should play the program/channel rather than opening the context menu section.

**Comment by primaeval** [comment]
The main reason I use Listings views is to look through days of listings fast and then watch any interesting ones on catchup.
The select needs to go to the menu so that I can select Meta4Kodi or iSearch to search for the catchup sources. 
Play is rarely needed for that use case.

**Comment by im85288** [comment]
Out of curiosity was this addon based on the iVue addon? I saw it being recommended in some forums today so googled it http://ivuetvguide.com and noticed it was pretty much identical..with the exception that this version has more features/full screen and allows a custom xmltv guide to be set. I think that one goes off and gets the xmltv for you based on your channel package and charges for the privilege.

**Comment by im85288** [comment]
Fair enough for that view, but if we do create a full now listing where it could be used in place of the EPG then select would be better off playing (as it does in the EPG) and using context menu would be best to bring up the menu

**Comment by primaeval** [comment]
I pulled in lots of ideas from all the different variations of TV Guide.
This one started as the FTV Guide fork.
I think noobsandnerbs had some good ideas with different categories based on different xmltv files.
But I think we are the most fully featured right now.
Nobody has the Browse \ Add Folder functionality and customization categories.
All your windows have upped the level to the premiere league now.

**Comment by primaeval** [comment]
The Next view needs the context menu too because you might choose to Autoplay the channel or just Remind you. You might want to see more of the description or set a new channel for it.

**Comment by im85288** [comment]
Haha great! It's the first one I used and thankfully I chose wisely 👍 

Never heard of noobsandnerds..time to Google

**Comment by primaeval** [comment]
Remember "good artists borrow, great artists steal." ;)
If its a good feature and open source then bring it on in.

**Comment by im85288** [comment]
Agree on the next view as you wouldn't want to immediately playback that program, autoplay is another new one to me. Lots under the hood going on!

**Comment by primaeval** [comment]
I've got something working with Autoplay but its going to be a bit tricky to get it to nicely integrate with the epg.

**Comment by im85288** [comment]
Sweet...now sidetracked on this meta4kodi addon...reading it now it looks very good.

**Comment by primaeval** [comment]
Its not as good as it was because the big name addons have blocked it. 
iSearch can get around that if you use Super Favourites from Spoyser's repo directly.

**Comment by im85288** [comment]
Ahh thanks for the tip, will check that out thanks.

**Comment by primaeval** [comment]
The My Subscriptions addons has ways to get round it too but I haven't worked out how to link that in.
That is good when you have added strm files into your library and you want to play them in another addon.

**Pull request closed without merging**
