### PR TITLE
AltChannel Background and Recording Update

### PR DESCRIPTION
**Pull request by Doctor-Eggs**
Provide an alternate background for the channel column in the guide. If the file tvg-alt-channel-column.png exists it will be used where the channel names/logos are located.

Allow for notification/autoplay/autoplaywith of only new episodes of a TV show.

Move autoplaywith recordings into seperate folders for Movies and TV Shows to provide better library integration.

### CODE REVIEW

**Comment by primaeval** [comment]
That's a big change. Are you sure it works and with the other skins?

The autoplaywiths might be a bit more complicated because I left it open to being any kind of automation not just recordings.

It's a very good idea though. I'll have to try it out and see.

**Comment by Doctor-Eggs** [comment]
I've tested it with Default and Catbar skins and no issues. I know with the previous commit I created a control that didn't exist in the other skins. This change looks for the .png file first and if it's there then it uses it. If not, it will just use the default.

That autoplaywith feature is awesome. Maybe a toggle in Settings >> Program Scheduler for seperating the Movies and TV Shows?

Also, for the is_new to work, the xmltv.xml will have to have the <new /> tag. I know some xmltv generators don't do it but zap2xml does.

**Comment by primaeval** [comment]
Thanks. 

I was hoping the new filter was just using your previous records as a filter but I suppose if a channel reruns something you will end up recording a thousand episodes that you've already seen.

Have you played with the new IPTV Recorder addon? The is_new filter might be useful there and some of the recording modes in that might be useful here.

**Comment by Doctor-Eggs** [comment]
You've been kicking ass with these addons. I've been meaning to check out IPTV Recorder and the XMLTVMeld but haven't had the time.

When I do I'll look into some of the different recording modes.

**Comment by primaeval** [comment]
The irony is I hardly ever watch tv but hopefully the kids will appreciate it if they ever get off youtube.

**Comment by primaeval** [comment]
I'll give it a go and trust you. If someone comes crying I'll send them to you.

**Comment by Doctor-Eggs** [comment]
Sounds good. Here's hoping there isn't that much crying. 
Thanks.

**Comment by primaeval** [comment]
It's in the repo now. Do you want to write a post about how to use it.

**Comment by Doctor-Eggs** [comment]
Done.

**Comment by primaeval** [comment]
Thanks.

**Pull request merged**
