### PR TITLE
up next feature

### PR DESCRIPTION
**Pull request by im85288**
pops up a up next info for the next episode (I added defaults to the default/pip/dark) skins

### CODE REVIEW

**Comment by im85288** [comment]
Was that comment about the logic addressed at this PR? The changes are in the dark skin too as I pulled it in just after your merge.

**Comment by im85288** [comment]
Somehow my last change wasn't in properly. This last one should fix that.

**Comment by primaeval** [comment]
I think that needs another pull from the main master. I tweaked the progress bar in Default and pip.

**Comment by im85288** [comment]
Is that correct now? I rebased a couple of times to be sure

**Comment by primaeval** [comment]
You re-enabled the threading timer. Do you need it? I was trying to fix the android bug and found it didn't seem to be necessary any more.

**Comment by im85288** [comment]
Yeah it's what the next up feature uses for updating the info when the timer gets close to the end of the program.

**Comment by primaeval** [comment]
Ok. Lets give it a go.

**Comment by primaeval** [comment]
Could you see if you can get the other skins to match up with the next program feature. I tried and managed to get it to crash out when it reached the next program time.

**Comment by im85288** [comment]
Strange, I thought I had it disabled by default for the other skins and it certainly should not crash. Was there anything in the log? I'm not in the house for a while so will not be able to look at the minute.

**Comment by primaeval** [comment]
I tried to copy the 8000 group to a 9000 group in Default but I got the crash when I enabled it.
Are there some extra controls that need creating?

**Comment by im85288** [comment]
Yes 9012 was added, I put that there in the PR. It contains the countdown time in seconds

**Comment by primaeval** [comment]
The main epg progess bar shows values when you aren't on the current program. Shouldn't it show zero?

**Comment by im85288** [comment]
It should be zero for programs that have not yet started. Completed ones it should be 100 and in progress ones show the current state.

**Comment by primaeval** [comment]
It definitely shows a lowish value but you have done a label trick to disable the whole progress bar even it isn't the current time.

**Comment by im85288** [comment]
Not sure I follow, it works correctly for me in my tests. Yes I do hide it when it's blank as that's programs that have not started yet

**Comment by primaeval** [comment]
I think there is something screwy with my main progress bar. If I force a 0 it still shows a value.

**Comment by primaeval** [comment]
Found it. If I use your textures it works. If I use mine it gives crazy values.

**Comment by im85288** [comment]
Strange stuff...at least you found it though :)

**Comment by primaeval** [comment]
Its the border=3 not the texture that fixed it in the end. Very strange.

**Comment by im85288** [comment]
Skinning can be a pain, it all depends on what size the progress bar is etc

**Comment by primaeval** [comment]
I think the up next window could do with a key to toggle it. If you set it up with minutes to go it could get annoying.

**Comment by im85288** [comment]
Haha yes, 20 seconds is more than enough. Having a dismiss key would be useful though.

**Comment by primaeval** [comment]
I just released 0.0.77.
I think iainmacleod might need some help with the Up Next popup. It was a bit tricky to swap the next and current channel controls around.

**Comment by im85288** [comment]
Cool, the best thing to do is look at the sly skin as I commented it in the descriptions.

**Comment by iainsmacleod** [comment]
Will do, 9000 range, 9012 added it my summary from reading.

**Pull request merged**
