### PR TITLE
More tweeks to the sly skin

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by primaeval** [comment]
Looks good.

The changes to gui.py break the other skins. So that needs fixing first.

The lower left progress bar doesn't look good to me, especially when there is no image. Is it there for a special reason?

The default image in the osd is nice but distracting to me because there is so much detail to look at. I think something plain or more abstract might show that it is for missing images. It also should match the main epg for missing images too.

Thanks for your help.

**Comment by im85288** [comment]
Whoops, I thought I had done the changes in gui.py in a way that the other skins did not need the new controls I added.

My initial plan was to use the progress bar only in the lower left position but that changed when I noticed it wasn't very good for PIP. Furthermore I never had any missing images and thought there was a default one specified. But I'm happy enough for that to be removed.

Again feel free to change the default "tv.jpg" image if it's distracting you...luckily I hardly ever see it as the channels from xmltv almost always have associated images. I'm pretty sure I used the same "tv.jpg" as a missing image for both the OSD and EPG but if I didn't then yes I agree they should be the same

**Comment by im85288** [comment]
I updated the other skins so as not to crash and removed the lower left progress bar. Hopefully it's better now :)

**Comment by primaeval** [comment]
Thanks. 
I'm trying to sort out the bad behaviour quirks at the moment. If you spot any please let me know.

**Comment by im85288** [comment]
I haven't noticed anything but will do If I spot any. Do you know where the background is controlled for the epg part? I wanted to add some opacity to the epg guide for the sly skin but there always seems to be a solid black background regardless of what I change.

Was also thinking a possible nice to have feature would be to search the epg...but maybe one for a rainy day!

**Comment by im85288** [comment]
Also maybe having a quick option to play the last played channel would be good. When using the pvr section in Kodi pressing "0" plays back the last played channel. I wonder if we can do something similar here?

**Comment by primaeval** [comment]
I'm not sure at the moment. The way I find out which texture is which is to make the texture background-cover.png or background-cover2.png. Then they stand out as bright green or red.

**Comment by primaeval** [comment]
I'm having a look at the osd commands at the moment. I'm trying to stop it popping back into the epg on channel up/down.

**Comment by im85288** [comment]
Ah yes I only get that when the stream takes some time to load. The one's I have that are connected to my pvr backend almost always stay on the fullscreen. I think I'm defeated in finding where the default background is for the epg. No biggie though

**Comment by im85288** [comment]
Actually scrap that analysis...it happens without a set pattern.

**Comment by primaeval** [comment]
That is what freaks me out too. I think I have found a pattern to fix and poof it changes.

**Comment by im85288** [comment]
Just added a quick fix to fallback to tv.jpg when no channel image is found in the epg...it looks like there are now conflicts on this PR though 👎

**Comment by primaeval** [comment]
I've done a few changes today. Can you pull them into your branch.

**Comment by im85288** [comment]
hopefully that resolved it...though sometimes with git and merging I find unhidden problems!

**Comment by primaeval** [comment]
It seems ok on windows. I'll try android a bit later.

In the main epg if there is no channel logo the name doesn't show up either. The channel name label is missing or disabled.

In the osd the channel name needs to go down a touch and probably align with the channel logo if possible.

**Comment by im85288** [comment]
Cool, I'll check the main epg thing..my channels always have logos so hadn't spotted that.

For the OSD, I'll take a look the intention is for the channel name to right align with the up/down arrows

**Comment by primaeval** [comment]
In the osd the progress bar looks like it should extend all the way across the middle panel. 
It is difficult to see where it ends because the panel border is blue too.

I think in the main epg the program description would be better as left justified like in the osd. Your call.

**Comment by im85288** [comment]
Cheers..will take a look. Thanks for the feedback :)

**Comment by primaeval** [comment]
I'm starting to sound really picky now, but your and iainmacleod's skin changes have upped the game.
It is starting to look pretty professional and polished. :)

**Comment by im85288** [comment]
I made a few changes, not sure what you were meaning with regards the program description on the main epg as that is justified text the same as the osd. new osd background should be clearer now

**Comment by primaeval** [comment]
This line:
https://github.com/im85288/script.tvguide.fullscreen/blob/f8acba9642ff72a683b0193ce76a90313ead6fed/resources/skins/sly/720p/script-tvguide-main.xml#L965
compared to this one that uses the default of left:
https://github.com/im85288/script.tvguide.fullscreen/blob/f8acba9642ff72a683b0193ce76a90313ead6fed/resources/skins/sly/720p/script-tvguide-main.xml#L1380

**Comment by im85288** [comment]
I see you what your saying now, but viewing them at the same time (EPG and OSD) I see no difference so I'm happy to leave it as it is.

**Comment by primaeval** [comment]
Its in now. Thanks.

**Pull request merged**
