### PR TITLE
show today/tomorrow for date labels epg

### PR DESCRIPTION
**Pull request by im85288**
Simple one for showing either Today/Tomorrow in the EPGs where applicable

### CODE REVIEW

**Comment by primaeval** [comment]
Could you add Yesterday please.

**Comment by im85288** [comment]
Yeah I can do when I'm back in about 20 mins. Does the EPG allow scrolling to yesterday's data? I thought it always started from the current day

**Comment by primaeval** [comment]
It does if you have some data in your xmltv file. After midnight you should have some unless you only grabbed one day of data.

**Comment by im85288** [comment]
No probs, I added it in now :)

**Comment by primaeval** [comment]
Thanks.

Something to watch out for is python 2.6 only functions for some devices: android especially.
I had to make a function for total_seconds earlier. 
There must be something stopping the move to python 2.7 on these devices.

**Comment by im85288** [comment]
Yeah I seen your change but have to admit to not knowing about that.

You mentioned a reminder thing earlier on (I think), so does that allow you to set a program on the EPG and then get reminded somehow when it's on? I saw some context menu stuff in the code but haven't seen how it's used.

**Comment by im85288** [comment]
Actually scrap that, I checked the code and am playing with it now. Seems pretty cool, I was thinking of implementing basically the same thing with the only difference being the notifications would happen probably half an hour before rather than 5 minutes and also show up at first start...but not sure how vital any of those would be 👍

**Comment by primaeval** [comment]
The feature that needs to be in here eventually is the play a program on the scheduler and stop afterwards.
I spent a lot of effort doing that the hard way years ago for my dad who ended up paralysed after an operation went wrong.
I had to use ir sensors attached to a printer port, windows 95 and a sky tv box.

**Comment by iainsmacleod** [comment]
How would he control it? You could use an Amazon Echo and use a skill so he
could ask for it to stop - if he still has vocal ability.

I use the Alexa add-on, it's ok. Needs a ton of work.

**Comment by primaeval** [comment]
I had voice recognition set up from whatever was best at the time and the microsoft text-to-speach with the little wizard character. He died a long time ago now, 2001.

**Comment by iainsmacleod** [comment]
I'm sorry for your loss, chief. It was amazing of you to come up with such
a solution. Good son.

Regarding your request - Only problem I see with scheduled stops is that
you can't really trust schedules. Maybe it is something like the next up
feature that Ian created, instead if autoplay, autostop unless cancelled.

**Comment by iainsmacleod** [comment]
I always get a black screen on Comet, OTA. I'll have to look into the
codec, maybe it is similar to your Android issue.

**Comment by primaeval** [comment]
Did you use plugin.video.comettv for Comet?
I've opened up a bug issue at Kodi Trac and Koying is having a look at the black screen issue.

If the schedules change there is not a lot you can do in an xmltv based player.

You need a pre and post buffer time to make sure you don't miss the start and end of the program.
The surprisingly tricky part of the logic is making sure that you don't stop the channel prematurely when two scheduled programs follow each other.

At the moment the Remind function matches everything but a scheduled Play function needs to be specific to one time, daily or weekly.

**Comment by iainsmacleod** [comment]
I just use an antenna for Comet. It's mpeg2.

**Pull request merged**
