### PR TITLE
Layout changes

### PR DESCRIPTION
**Pull request by iainsmacleod**
Fixed a bunch of small highlight errors

### CODE REVIEW

**Comment by primaeval** [comment]
Did you pull in my changes because the menu 4009 button doesn't seem to be there?

**Comment by iainsmacleod** [comment]
I did pull in your changes. I noticed some buttons don't show up on menu -
had a quick look as to what was going on, didn't see anything obvious. I'll
have to work on it later. Got my kid this weekend.

**Comment by primaeval** [comment]
The buttons don't show up if you don't have 4009. It crashes with an exception when the gui.py tries to access it.

Have fun with your kid.

**Comment by iainsmacleod** [comment]
FIxed, is there any references that are in places other than menu? Like, is there are autoplaywith highlight color?

**Comment by primaeval** [comment]
Yes there is an autoplaywith highlight. I might have added it to yours and I might not. ;) 
The textures need to be added at the top of main like the others if I forgot.

**Comment by iainsmacleod** [comment]
Should be it

**Pull request merged**
