### PR TITLE
Updated layout and image

### PR DESCRIPTION
**Pull request by iainsmacleod**
Added weather info

### CODE REVIEW

**Comment by primaeval** [comment]
Are you sure about adding the weather? There isn't that much space to show all the necessary info already, especially on small devices.

**Comment by iainsmacleod** [comment]
It's conditional, if someone doesn't want to use it in their skin it won't
be shown.

It looks good on my 3 boxes. I'm not sure that many people use my skin -
I'll see what the feedback is.

**Comment by primaeval** [comment]
I added in the 4009 AutoPlayWith button on my playwith branch. I had to move the buttons up a bit. I'll probably bring the whole branch into master soon so you can have a look. If you try that branch beware that it will change the source.db structure a bit, so you'll need to be careful moving back to master.

**Comment by iainsmacleod** [comment]
I use my desktop for testing, so I'll just download the zip, load it and a
try it out.

Thanks.

**Pull request merged**
