### PR TITLE
Updated version of Dark skin

### PR DESCRIPTION
**Pull request by iainsmacleod**
Made several changes to the UI, more transparent, modified some
additional screens, changed some highlight colors. PLease review, as I was seeing an issue with the selected channel highlight, and the time bar - however all skins tested the same - maybe it is an issue on my windows box?

### CODE REVIEW

**Comment by primaeval** [comment]
Looks nice. Thanks.

The script-tvguide-streamaddon.xml dialog needs resizing. Try BBC One from plugin.video.iplayerwww to get a lot of potential matches and you will see.

The last page of the main dialog might need some work too. Compare Default and Dark.
The footer isn't distinct in Default but it reaches up to the last channel. Dark has lots of space.
I've been trying to get things to match up in gui.py by stretching the footer. 
It might need another texture to work properly.

The bottom of the epg section doesn't match up with the footer but that is something that needs to be fixed in gui.py too. It is a rounding error when calculating where the bottom of the channels should be.

**Comment by iainsmacleod** [comment]
I am not sure how to access the streamaddon.xml UI, I checked the plugin.video.iplayerwww folder to see what you were refering to, regarding checking out BBC One, but I don't see what you are talking about. Can you elaborate please?

I'll play about with the EPG guide and footer - the issue is that the addon can have a variety of entries displayed (up to 16), and this ends up having alternate spacing between the footer and the last page item.

For example, I am displaying 9, and it doesn't line up . "Compare Default and Dark.
The footer isn't distinct in Default but it reaches up to the last channel" HOw many items are you displaying?

**Comment by primaeval** [comment]
Here you go. http://imgur.com/a/krz3n

I can't quite work out why I can't get the footer to resize properly in gui.py. Maybe you can work it out.

I'm still trying to work out why channels sometimes play behind the overlay on Android. 
Have you seen this bug?

**Comment by iainsmacleod** [comment]
How can I get stream add-on working in my environment? I'm not sure how to
do this, is this related to the add-on.ini? I really need to get it working
to see it first hand.

I have an Android phone, I will install and investigate.

The guide issue I'll have to look into, I think it would best be handled as
a static list - rather than paging, so we have a set size to work with.
Like when you are doing channel setup - it doesn't page, it wraps.

**Comment by iainsmacleod** [comment]
Ok, I have made changes and will submit a new pull request with the modification thus far.

**Comment by iainsmacleod** [comment]
So I believe I merged your changes into my branch, but I am unable to make another pull request - merely view?? Any suggestions? I committed the changes to my master and synced remote and local...

**Comment by iainsmacleod** [comment]
I get an error on my new pull request saying that it "could not create pull request, try manually syncing current branch and target branch". I have tried, but I also get an error when trying to sync your branch - "failed to sync this branch".

**Comment by primaeval** [comment]
I reset my master branch to get rid of some android fixes that didn't work in the end.
You'll have to do another pull or fetch.

**Pull request closed without merging**
