### PR TITLE
show the now playing program with a different texture to highlight it

### PR DESCRIPTION
**Pull request by im85288**
uses tvguide-program-grey and tvguide-program-grey-focus for the now playing program in the epg

### CODE REVIEW

**Comment by primaeval** [comment]
Could you have a go at passing the highlight using a dummy control so its easy to add new skins.
I made a few changes that are too specific too in redrawEPG that need making more generic.

**Comment by im85288** [comment]
Not sure how that would work at the minute...as this one is the control button that is used for the epg layout and I'm still not exactly sure how all that works. 

With the change as it is skins just need to change the tvguide-program-grey pngs in their own media folder

**Comment by primaeval** [comment]
Be careful with detailed textures. 
I had to change to the plain black-back.png because android and rpi couldn't cope with the original textures when there were more than 8 channels and lots of programs in the epg view.
It must have been an out of memory or resources error.
Using simple textures fixed it.

**Comment by im85288** [comment]
Ah thanks, I had noticed textures not showing up and even occasionally have it with the grey ones I started using. I'll keep an eye on it if it happens again cheers.

**Comment by primaeval** [comment]
If this gets into the official repo we have to make sure it works on all the devices supported by Kodi.

**Comment by primaeval** [comment]
I'm having real problems making png textures with transparency that kodi likes.
What do you use?

**Comment by im85288** [comment]
Yeah I've had a lot of problems trying to get the epg to show consistently with any other pngs than black-back.png and tvguide-program-red.png so reverted back my previous change for the sly skin. I use photoshop but badly...not my strongest point messing around with textures

**Comment by primaeval** [comment]
I've tried Gimp too with no luck. There must be a format trick but I can't find it in the forum.

**Comment by primaeval** [comment]
This is driving me nuts now. I've posted a question in the skinning forum.
Some transparent images from Confluence work, some don't.
Estuary ones from 17.0 don't work.

**Comment by iainsmacleod** [comment]
I use gimp for creating images.

**Comment by primaeval** [comment]
I solved it. Textures used in the code need to be preloaded in the xml files.
See https://github.com/primaeval/script.tvguide.fullscreen/pull/33#issuecomment-242798558

**Pull request merged**
