### PR TITLE
Skin fixes

### PR DESCRIPTION
**Pull request by iainsmacleod**
Updated various layout, maybe need to rename this transparent.

### CODE REVIEW

**Comment by primaeval** [comment]
You didn't check it on jarvis confluence did you?

**Comment by iainsmacleod** [comment]
I did not. I will. I have a bunch of changes I have to make first.

**Comment by primaeval** [comment]
Please don't submit a pull request until you have fully tested all the skins on jarvis confluence in future. I really don't have the time to fix other people's bugs. I have enough of my own to deal with.

**Comment by iainsmacleod** [comment]
Understood. Tried to apply my changes but my branch is a me. Have to work
out how to reset to you and submit a new pull.

Sorry for the inconvenience.

**Pull request merged**
