### PR TITLE
to small fixes

### PR DESCRIPTION
**Pull request by tycoo**
was a little late

### CODE REVIEW

**Comment by primaeval** [comment]
@tycoo I've made an addon for the custom font version. Could you make a version for the default font version and I'll get them in the repo.
https://github.com/primaeval/script.tvguide.fullscreen.skin.white_snow_CustomFont
The krypton branch needs StringCompare to be replaced with String.IsEqual.
Do you want to announce your skin in the forum when the repo is ready?

**Comment by tycoo** [comment]
@primaeval 
"The krypton branch needs StringCompare to be replaced with String.IsEqual."

Can't find it anymore? :/

**Comment by primaeval** [comment]
I did a global search and replace in the last krypton commit but be aware of the differences when you make changes and add the default font version.
https://github.com/primaeval/script.tvguide.fullscreen.skin.white_snow_CustomFont/commit/f144e93708cbb5c36aa4ff20d515fdba358badf1

**Comment by tycoo** [comment]
Ok, i got it. I will replace all for Krypton

DefaultFont for Jarvis is already up:
https://github.com/tycoo/script.tvguide.fullscreen/tree/white_snow_rework/white_snow_DefaultFont-ZIP

**Comment by tycoo** [comment]
Finally: 
https://github.com/tycoo/script.tvguide.fullscreen/tree/white_snow_rework/white_snow%20ZIPs%20for%20Krypton

**Pull request merged**
